### ISSUE TITLE
No <h1> or <h2> Heading tags !

### ISSUE THREAD

**Issue by yooozy** [puikinsh/Unite-Theme#17]
h1 and h2 tags are not used/assigned in this theme, it's extremely important for SEO.

**Comment by florianlenz** [comment]
What exactly do you mean? It works fine for me at a normal page (have a look at the screenshot). Please upload a screenshot of what you mean. 
![bildschirmfoto 2016-01-10 um 11 49 08](https://cloud.githubusercontent.com/assets/16626192/12221208/70bd17f4-b790-11e5-9f2e-7376b2e00f38.png)

**Comment by yooozy** [comment]
not that, my issue is that the unite theme is not assigning h1 h2  heading tags correctly, I use Uinte for http://www.everyonebmx.com, it's a shop , when analyzing it with woorank it says no h1 or h2 headings, https://www.woorank.com/en/www/everyonebmx.com so unite theme is not assigning h1 or h2, only h3 headings

**Comment by puikinsh** [comment]
@yooozy 

You have created your website so that there are absolutely no h1 and h2 tags. In this case it has very little to do with theme itself. 

You can manually add h1 and/or h2 within body of your page and you will be good to go. From theme perspective I can't do anything with your particular case.
