### ISSUE TITLE
add custom style in code?

### ISSUE THREAD

**Issue by prankousky** [puikinsh/Unite-Theme#29]
hi,

i am trying to add some custom css to unite theme (own.css). Where can I link this stylesheet so that it will be able to override standard styles?

I have tried adding `<link href="own.css" rel="stylesheet">
`to index.php. No success. I would rather work with a separate css file instead of using the "additional css" box.

Thank you in advance.

**Comment by puikinsh** [comment]
You should be using [wp_enqueue_style](https://developer.wordpress.org/reference/functions/wp_enqueue_style/) via `functions.php` or Child Theme `functions.php` insted of adding files directly to template files. 

For other support related questions please use our support forum https://colorlib.com/wp/forums/ since Github is for bug tracking and this is not a bug.
